### ISSUE TITLE
Search for Sms Enabled Toll Free Numbers

### ISSUE THREAD

**Issue by dmitriy-teledirect** [twilio/twilio-dotnet#1]
ListAvailableLocalPhoneNumbers allows us to pass AvailablePhoneNumberListRequest parameter. In AvailablePhoneNumberListRequest we can specify SmsEnabled = True. 

We need the same functionality for ListAvailableTollFreePhoneNumbers. Right now its not possible for us to pull Toll Free numbers that are SMS Enabled.

**Comment by devinrader** [comment]
Just checked a fix for this into Github.  It will get included in the next push to nuget.

**Comment by dmitriy-teledirect** [comment]
When is the next push to nuget? Last publish date is 2/26/2015. We purchase hundreds of numbers from Twilio every month. We need all numbers to be SmsEnabled. Right now we have to manually check every number after the purchase.
