### ISSUE TITLE
Master Twilio Account Credentials 

### ISSUE THREAD

**Issue by dmitriy-teledirect** [twilio/twilio-dotnet#2]
We want to use master Twilio account credentials when using twilio.RedirectCall for the subaccount's phone call. Twilio Customer Support stated "Yes, this should be possible, however the .NET helper library doesn't support the operation, even though the lower level REST API does."

For us it would be a major redesign to use subaccount's credentials. We need subaccounts just for billing purposes. Since Twilio REST API does allow master Twilio account to modify phone calls of the subaccounts,  can the .NET helper library be modified to match that behavior?

**Comment by devinrader** [comment]
Hey @dmitriy-teledirect.  Both this beta library and the released library (here) should support this.  There is a constructor overload that lets you specify a accountsid and authtoken to authenticate with, as well as another accountsid that will be used as the resource to make the change to:

    var client = new TwilioRestClient("[AccountSid]", "[AuthToken]", "[SubAccountSid]");

Using this constructor tells the .NET lib to use the SubAccountSid when it builds the REST API Urls:

    /2010-04-01/Accounts/{SubAccountSid}/Calls/{CallSid}

Pretty sure that will let you do what you want.  If not, let me know and I'll investigate further.
